Changes sent as list instead of one by one.
jupyterlab/rtc pull request #105
Opened 2021-01-16 07:48 UTC by pierrotsmnrd

Changes from Automerge are now sent as list of changes, instead of being sent one by one. 
Fixes the behavior when reloading the page : all changes are now applied at once.

2021-01-16 08:05 UTC, echarles requested changes
Thx @pierrotsmnrd I have added minor feedback related to commented line. I see you convert the array of changes in json. Have you tried to still send them in binary and just apply them as they are on the client?

2021-01-16 08:05 UTC, echarles commented on automerge/jupyter_rtc/handlers.py
> +        #print(f"\nDEBUG message : {message}")
Maybe remove this commented line?

2021-01-16 08:05 UTC, echarles commented on automerge/packages/jupyterlab-rtc/src/index.ts
> +          // const data = new Uint8Array(message.data);
Maybe remove this commented line?

2021-01-16 08:05 UTC, echarles commented on automerge/packages/jupyterlab-rtc/src/index.ts
> +          // const data = new Uint8Array(message.data);
Maybe remove this commented line?

2021-01-16 08:05 UTC, echarles commented on automerge/jupyter_rtc/handlers.py
> +        #print("DISPATCH PAYLOAD : ", payload)
Maybe remove this commented line?

2021-01-18 09:12 UTC, pierrotsmnrd commented on automerge/jupyter_rtc/handlers.py
> +        #print(f"\nDEBUG message : {message}")
Done

2021-01-18 09:12 UTC, pierrotsmnrd commented on automerge/packages/jupyterlab-rtc/src/index.ts
> +          // const data = new Uint8Array(message.data);
Done

2021-01-18 16:49 UTC, echarles approved these changes
Thx @pierrotsmnrd

2021-01-18 16:50 UTC, merged